#------------
- hosts: linuxservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: kasper
  become: yes
  tasks:

  - name: standaard vim en git
    apt:
          name: "{{ packages }}"
          state: present
    vars:
          packages:
                  - git
                  - vim

  - name: git map aanmaken
    file:
      path: /home/kasper/git
      state: directory
      owner: kasper
      mode: 0775

#------------
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: kasper
  tasks:
  - name: ensure nginx is at the latest version
    apt:
          name: "{{ packages }}"
          state: present
    vars:
          packages:
                  - nginx
                  - php7

  - name: write the apache config file
    template:
      src: /srv/nginx_conf.j2
      dest: /etc/@@@@.conf
    notify:
    - restart nginx
  - name: zekerweten dat nginx runt
    service:
      name: nginx
      state: started
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

#------------
- hosts: linuxservers
  vars:

  remote_user: kasper
  become: yes
  tasks:
  - name: standaard vim en git
    apt:
          name: "{{ packages }}"
          state: present
    vars:
          packages:
                  - vim
                  - git
  - name: minecraft map aanmaken
    file:
      path: /games/minecraft
      state: directory
      owner: kasper
      mode: 0775
      recurse: yes

  - name: Minecraft downloaden 
    get_url:
     url: https://launcher.mojang.com/v1/objects/3dc3d84a581f14691199cf6831b71ed1296a9fdf/server.jar
     dest: /games/minecraft/minecraft_1.14.jar
     owner: kasper
     mode: 775
    
  - name: mc start file downloaden
    git:
     repo: 'https://github.com/KasperGit/games.git'
     dest: /home/kasper/Downloads/games.git

  - name: mc start file kopieren en ex maken
    copy:
     remote_src: True 
     src: /home/kasper/Downloads/games.git/minecraft_start
     dest: /home/kasper/
     mode: +x

  - name: mc licentie accepteren
    copy:
     remote_src: True
     src: /home/kasper/Downloads/games.git/eula.txt
     dest: /games/minecraft

  - name: server properteis kopieren
    copy:
     remote_src: True
     src: /home/kasper/Downloads/games.git/server.properties
     dest: /games/minecraft

  - name: villagers world map aanmaken
    file:
      path: /games/minecraft/village_world
      state: directory
      owner: kasper

  - name: server bestanden kopieren
    copy:
     remote_src: True
     directory_mode: yes
     src: /home/kasper/Downloads/games.git/village_world 
     dest: /games/minecraft/village_world


 # - name: minecraft starten
 #   command: ./minecraft_start